### ISSUE TITLE
[CHECKLIST] Checklist before release to public

### ISSUE THREAD

**Issue by johncalesp** [CentML/flexible-inference-bench#53]
Test Flexible Inference Benchmark with the following conditions:
**Model:** meta-llama/Llama-2-13b-hf
**Hardware:** GCP V100x4 (Similar to Wells Fargo infra)
**Tasks:**
- [x] PP (isolated)
- [x] TP (isolated)
- [x] ~~Offloading~~ (super slow)
- [x] PP + TP
- [x] ~~PP + Offloading~~
- [x] TP + Offloading
- [x] ~~PP + TP + Offloading~~
- [x] Add simple example in README
- [ ] Reset commit history
